---
vault_version: "0.11.1"
vault_checksum: "sha256:eb8d2461d0ca249c1f91005f878795998bdeafccfde0b9bae82343541ce65996"
vault_install_prerequisites: ['unzip']
vault_user: "vault"
vault_group: "vault"
vault_config_path: "/etc/vault.hcl"